### ISSUE TITLE
2021 Roadmap

### ISSUE THREAD

**Issue by flleeppyy** [flleeppyy/kofi-darkmode#3]
This is the roadmap/goals for this project throughout 2021

- [x] Convert to SCSS
- [ ] Clean up SCSS after converting (CSS->SCSS via [BeautifyTools](http://beautifytools.com/css-to-scss-converter.php))
- [ ] Use variables for colors to stay organized

More tasks will be added as the year progresses.
